Fixed options

diff --git a/scripts/get_basis b/scripts/get_basis
--- a/scripts/get_basis
+++ b/scripts/get_basis
@@ -39,10 +39,10 @@ do
 done
 
 if [[ $? -ne 0 ]] ; then
-  echo "==================================================" 1>& 2
-  echo "Unable to create temporary file $tmpfile" 1>& 2
-  echo "==================================================" 1>& 2
-  echo "ERROR"
+  >&2 echo "=================================================="
+  >&2 echo "Unable to create temporary file $tmpfile"
+  >&2 echo "=================================================="
+  >&2 echo "ERROR"
   exit 1
 fi
 
